Needed Things and SwerveModule
goldenhornfrc/2023-offseason-rewrite pull request #2
Opened 2023-11-22 19:11 UTC by KeremAlp01

alliance,vendor,state and SwerveModule

2023-11-22 19:35 UTC, emrecandabak requested changes

2023-11-22 19:35 UTC, emrecandabak commented on src/SwerveModule.java
> +        angleOffsett = moduleconstans.angleOffsett;
fix typo -> angleOffset

2023-11-22 19:35 UTC, emrecandabak commented on src/SwerveModule.java
> +    private void configangleEncoder() {
camelCase

2023-11-22 19:35 UTC, emrecandabak commented on src/SwerveModule.java
> +        anglemotor = new CANSparkMax(moduleconstans.angleMotorID,MotorType.kBrushless);
camelCase

2023-11-22 19:35 UTC, emrecandabak commented on src/SwerveModule.java
> +        drivemotor = new CANSparkMax(moduleconstans.driveMotorID,MotorType.kBrushless);
camelCase

2023-11-22 19:35 UTC, emrecandabak commented on src/SwerveModule.java
> +        angleEncoder.configAllSettings(null);
??

2023-11-22 19:35 UTC, emrecandabak commented on src/SwerveModule.java
> +        integradetAngleEncoder.setPosition(absolutePosition);
integratedAngleEncoder

2023-11-22 19:35 UTC, emrecandabak commented on src/SwerveModule.java
> +        drivemotor.getInverted();
getInverted?

2023-11-22 19:35 UTC, emrecandabak commented on src/SwerveModule.java
> +        drivemotor.getIdleMode();
getIdleMode?

2023-11-22 19:35 UTC, emrecandabak commented on src/SwerveModule.java
> +        driveController.getP();
get her şey???

2023-11-22 19:35 UTC, emrecandabak commented on src/SwerveModule.java
> +        drivemotor.enableVoltageCompensation(12);
burnFlash en son yapılmalı her zaman

2023-11-22 19:35 UTC, emrecandabak commented on src/SwerveModule.java
> +            double percentoutput = desiredState.speedMetersPerSecond / 4.5;
4.5 elle yazılmayacak,  constant olmalı

2023-11-22 19:35 UTC, emrecandabak commented on src/SwerveModule.java
> +        Rotation2d angle = (Math.abs(desiredState.speedMetersPerSecond) <= (4.5 * 0.01)) ? getAngle() :desiredState.angle;
4.5 elle yazılmayacak

2023-11-22 19:37 UTC, KeremAlp01 commented on src/SwerveModule.java
> +    private void configangleEncoder() {
configAngleEncoder?

2023-11-22 19:37 UTC, KeremAlp01 commented on src/SwerveModule.java
> +        anglemotor = new CANSparkMax(moduleconstans.angleMotorID,MotorType.kBrushless);
driveMotor?

2023-11-22 19:38 UTC, KeremAlp01 commented on src/SwerveModule.java
> +        drivemotor.getIdleMode();
neutral mode eklemeyecek miyim?

2023-11-22 19:39 UTC, KeremAlp01 commented on src/SwerveModule.java
> +            double percentoutput = desiredState.speedMetersPerSecond / 4.5;
tamamdır constantları en son ayarlicam hata veriyordu 4.5 ondan yazdım 0.01 de constant

2023-11-22 19:40 UTC, KeremAlp01 commented on src/SwerveModule.java
> +        angleOffsett = moduleconstans.angleOffsett;
efsanevi ingilizcem

2023-11-22 19:40 UTC, KeremAlp01 commented on src/SwerveModule.java
> +        angleEncoder.configAllSettings(null);
nullu doldurmayı unutmuşum ayriyetten bir şey var mı

2023-11-22 19:41 UTC, KeremAlp01 commented on src/SwerveModule.java
> +        driveController.getP();
bunlarda setmiş

2023-11-22 19:43 UTC, emrecandabak commented on src/SwerveModule.java
> +        angleEncoder.configAllSettings(null);
> nullu doldurmayı unutmuşum ayriyetten bir şey var mı

yok

2023-11-22 19:43 UTC, emrecandabak commented on src/SwerveModule.java
> +        drivemotor.getIdleMode();
> neutral mode eklemeyecek miyim?

setlemen lazım o zaman

2023-11-23 17:58 UTC, emrecandabak requested changes
spotless ve pre-commit çalıştır ayrıca

2023-11-23 17:58 UTC, emrecandabak commented on src/main/java/frc/lib/util/CTREConfigs.java
> +  public CANCoderConfiguration swerveCanCoderConfig;
swerveCANCoderConfig

2023-11-23 17:58 UTC, emrecandabak commented on src/main/java/frc/robot/SwerveModule.java
> +        angleEncoder = new CANCoder(moduleconstans.cancoderID);
moduleConstants

2023-11-23 17:58 UTC, emrecandabak commented on src/main/java/frc/robot/SwerveModule.java
> +        angleEncoder = new CANCoder(moduleconstans.cancoderID);
CANCoderID

2023-11-23 17:58 UTC, emrecandabak commented on src/main/java/frc/robot/SwerveModule.java
> +        driveMotor.setIdleMode(null);
null?

2023-11-23 17:58 UTC, emrecandabak commented on src/main/java/frc/robot/SwerveModule.java
>          driveEncoder.getVelocityConversionFactor();
getler duruyor hala??

2023-11-23 17:58 UTC, emrecandabak commented on src/main/java/frc/robot/SwerveModule.java
>          angleController.getP();
pid değerlerini "getlemek" ne işine yarayacak tam olarak? konfigüre ederken setlemen lazım

2023-11-23 17:58 UTC, emrecandabak commented on src/main/java/frc/robot/subsystems/Swerve.java
> +       SwerveDriveKinematics.desaturateWheelSpeeds(swerveModuleState, 4.5);
4.5 yazmıyorsun elinle

2023-11-23 17:58 UTC, emrecandabak commented on src/main/java/frc/robot/subsystems/Swerve.java
> +    SwerveDriveKinematics.desaturateWheelSpeeds(desiredStates, 4.5);
4.5

2023-11-23 17:58 UTC, emrecandabak commented on src/main/java/frc/robot/subsystems/Swerve.java
> +  public void EstimatorWithVision(Pose2d measurement,double latency){
fonksiyon ismini düzelt

2023-11-23 17:58 UTC, emrecandabak commented on src/main/java/frc/robot/subsystems/Swerve.java
> +    return(true)?
bu ne?

2023-11-23 17:58 UTC, emrecandabak commented on src/main/java/frc/robot/subsystems/Swerve.java
> +  public void setisFieldOrieted(){
setFieldOriented*

2023-11-23 17:58 UTC, emrecandabak commented on src/main/java/frc/robot/subsystems/Swerve.java
> +  public void isRobotOriented(){
setRobotOriented

2023-11-23 18:00 UTC, emrecandabak requested changes

2023-11-23 18:00 UTC, emrecandabak commented on src/main/java/frc/robot/subsystems/Swerve.java
> +                null,
null?

2023-11-23 18:00 UTC, emrecandabak commented on src/main/java/frc/robot/SwerveModule.java
> +        driveEncoder.setPosition(0.0);
burnFlashtan sonra sıfırlaman lazım encoderi

2023-11-23 18:03 UTC, KeremAlp01 commented on src/main/java/frc/robot/SwerveModule.java
> +        driveMotor.setIdleMode(null);
hata veriyo yarın constant ekleyecem içine

2023-11-23 18:08 UTC, KeremAlp01 commented on src/main/java/frc/robot/subsystems/Swerve.java
> +    return(true)?
bende gözükmüyor bu

2023-11-23 18:10 UTC, KeremAlp01 commented on src/main/java/frc/robot/subsystems/Swerve.java
> +    return(true)?
invert gyro yerine yazdım constant ekledim mi hepsini değiştircem

2023-11-23 19:58 UTC, emrecandabak requested changes

2023-11-23 19:58 UTC, emrecandabak commented on src/main/java/frc/robot/subsystems/Swerve.java
> +  public void setFieldOrieted(){
oriented

2023-11-23 19:58 UTC, emrecandabak commented on src/main/java/frc/robot/SwerveModule.java
>          integradetAngleEncoder.setPositionConversionFactor(28);
integrated

2023-11-29 14:54 UTC, emrecandabak requested changes
Intake çalıştırma komutu, çekilen akıma göre obje olup olmadığını algılama, obje varsa tutma eklenmeli

2023-11-29 14:54 UTC, emrecandabak commented on src/main/java/frc/robot/subsystems/IntakeSubsystem.java
>      private StatorCurrentLimitConfiguration m_limit = new StatorCurrentLimitConfiguration();
Stator değil, supply limit yapmamız lazım. Konu hakkında detaylı bilgi: https://www.chiefdelphi.com/t/current-limiting-talonfx-values/374780

2023-11-29 14:54 UTC, emrecandabak commented on src/main/java/frc/robot/subsystems/IntakeSubsystem.java
>          intakeMotor.configOpenloopRamp(0);
OpenloopRamp constant olmalı. https://v5.docs.ctr-electronics.com/en/stable/ch13_MC.html#ramping ne olduğu ile ilgili bilgi

2023-11-29 14:54 UTC, emrecandabak commented on src/main/java/frc/robot/subsystems/IntakeSubsystem.java
>          m_limit.triggerThresholdCurrent = 0;
Bu değerler de constant olmalı, enable hariç

2023-11-29 14:54 UTC, emrecandabak commented on src/main/java/frc/robot/subsystems/IntakeSubsystem.java
>          intakeMotor.configStatorCurrentLimit(new StatorCurrentLimitConfiguration());
burası da değişeccek

2023-12-02 19:05 UTC, emrecandabak requested changes

2023-12-02 19:05 UTC, emrecandabak commented on src/main/java/frc/robot/RobotContainer.java
> +        new JoystickButton(driver, 0).onTrue(new InstantCommand(() -> {m_swerve.setWantsHeadingLock(true);}))
0. buton diye bir şey yok

2023-12-04 14:56 UTC, merged